# Generated by Django 4.1.3 on 2022-11-27 23:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaEstiba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_serie', models.CharField(max_length=255, unique=True)),
                ('precio', models.IntegerField()),
                ('cant_medi', models.IntegerField()),
                ('fecha_creacion', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['no_serie', 'fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='TipoMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('nombre', models.CharField(max_length=255)),
                ('no_lote', models.CharField(max_length=255, unique=True)),
                ('fecha_cad', models.DateField(default=datetime.datetime(2027, 11, 26, 23, 6, 20, 810745, tzinfo=datetime.timezone.utc))),
                ('tarjeta_estiba_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main_app.tarjetaestiba')),
                ('tipo_medicamento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tipomedicamento')),
            ],
            options={
                'ordering': ['fecha_cad', 'no_lote', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_medicamento', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('medicamentos', models.ManyToManyField(to='main_app.medicamento')),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('tarjeta_bancaria', models.CharField(max_length=255)),
                ('total_pagado', models.IntegerField()),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medicamentos', models.ManyToManyField(to='main_app.medicamento')),
            ],
        ),
    ]
