# Generated by Django 4.1.3 on 2022-11-27 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_tarjetaestiba_tipomedicamento_medicamento_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='fecha_cad',
            field=models.DateField(default=datetime.datetime(2027, 11, 26, 23, 0, 22, 403911, tzinfo=datetime.timezone.utc)),
        ),
    ]
